### ISSUE TITLE
Add "markdown" visualizator for STRING types

### ISSUE THREAD

**Issue by PhantomYdn** [PhantomYdn/Orienteer#132]

**Comment by krichter722** [comment]
Do you have a (possibly maven based) library in mind which allows markdown -> HTML transformation and maybe syntax highlighting so that it can be used in in an `IVisualizer` implementation?

**Comment by PhantomYdn** [comment]
Good question... Several years age I used `markdown4j`: but it seems outdated and not maven. But it seems that following library is good enough: https://github.com/sirthias/pegdown Hopefully it will not bring a lot through dependencies: I'm trying to keep Orienteer tiny.

**Comment by PhantomYdn** [comment]
Implemented in #163
