### ISSUE TITLE
Define code formatting rules and setup a formatter or the maven checkstyle plugin

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#147]
Currently there's a wild mixture of tabs and spaces (4 or 8) being used for indentation (some even mixed in the same file). I'd suggest 4 spaces indentation (no tabs due to incompatibility with mailing lists) for all files (java, XML, etc.) and use checkstyle rather than a formatter. Document everything is `HACKING` or `CONTRIBUTING`. I'd be willing to do it, just assign me.

**Comment by PhantomYdn** [comment]
You are welcome to do that!
If you need code change: PR. If you want to change documentation: my idea was to use github wiki for that. There is already [development documentation](https://github.com/PhantomYdn/Orienteer/wiki#development-documentation). Feel free to contribute in Wiki as well!

**Comment by krichter722** [comment]
Btw, I'll licence all files which are missing a header (I didn't find one single after superficial search) as described in `LICENSE` with you name. What copyright year/years should I take (should be the one `LICENSE` was added to the public repository, right?)?

**Comment by krichter722** [comment]
I think you need to used different keywords in commits. This is closed, right?

**Comment by PhantomYdn** [comment]
I guess we can close this. But sometime before release I will reformat spacing.

**Comment by krichter722** [comment]
The `check_style.xml` you created is fine. Maybe remove the spaces and enforce indentation at some point.

**Comment by PhantomYdn** [comment]
Yea... Also will enforce JavaDocs once it will be ready.
