### ISSUE TITLE
Allow krichter722 self-assignment of issues

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#164]
Hi, in #152 you offered to give me some privileges of the repository. I'd appreciate it if I could assign some issue to myself.

**Comment by PhantomYdn** [comment]
Thanks for this issue. It seems that Orienteer should be converted to organization in github to allow to add members to a team. Will work on it.

**Comment by krichter722** [comment]
Don't bother with it if unless it can be set up trivially.

**Comment by krichter722** [comment]
More of topic to be discussed in the chat -> https://gitter.im/krichter722/Orienteer-permissions in place of a mailing list

**Comment by PhantomYdn** [comment]
It seems work now:)

**Comment by krichter722** [comment]
Yes, thank you for the invitation to become a team member.
