### ISSUE TITLE
Allow command line arguments of standalone jar to be configurable in webfrontend at runtime

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#174]
It'd be great if the database connection would be configurable (including a switch for connecting to the (or even multiple) embedded instance(s)). I can't think of any other option I'm missing to configurable at runtime in the web frontend, but I formulated the title as abstract as possible.

**Comment by PhantomYdn** [comment]
Yea - I have issue for that: #125 
I moved your comment to that issue

**Comment by PhantomYdn** [comment]
Please let me know how it's important for you?
Btw: please take a look into my last comment on that issue (#125): is it good design from your point of view?
